name: CI

on:
  pull_request:
    branches: [main]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: restore cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: install
        run: yarn install --frozen-lockfile --check-files
        # cache the working directory so we can use it in other jobs without having to checkout and install
      - uses: actions/cache@v2
        with:
          path: ./**
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
  lint:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: restore source code
        uses: actions/cache@v2
        with:
          path: ./**
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn lint:all
  test:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: restore source code
        uses: actions/cache@v2
        with:
          path: ./**
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn test
  type_check:
    name: type check
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: restore source code
        uses: actions/cache@v2
        with:
          path: ./**
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn type-check
