name: Publish
on:
  push:
    branches:
      - main
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: restore cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: install
        run: yarn install --frozen-lockfile --check-files
        # cache the working directory so we can use it in other jobs without having to checkout and install
      - uses: actions/cache@v2
        with:
          path: ./**
          key: ${{ github.sha }}
  publish:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: restore source code
        uses: actions/cache@v2
        with:
          path: ./**
          key: ${{ github.sha }}
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - run: npx semantic-release@17
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
