name: Publish
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: restore cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: install
        run: yarn install --frozen-lockfile --check-files
        # cache the working directory so we can use it in other jobs without having to checkout and install
      - uses: actions/cache@v2
        with:
          path: ./**
          key: ${{ github.sha }}
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - run: npx semantic-release@17
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
